//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int EventId { get; set; }
        public string EventTitle { get; set; }
        public string EventOwner { get; set; }
        public System.DateTime EventDay { get; set; }
        public Nullable<int> Candidate_Id { get; set; }
    
        public virtual Candidates Candidates { get; set; }
    }
}
