//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobAdverts
    {
        public int Id { get; set; }
        public string JobDescription { get; set; }
        public string JobTitle { get; set; }
        public string CityName { get; set; }
        public string OpenPosition { get; set; }
        public bool IsActive { get; set; }
        public int EmployerId { get; set; }
        public Nullable<int> Employer_EmployersId { get; set; }
        public Nullable<int> City_CityId { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Employers Employers { get; set; }
    }
}
