//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobExperiences
    {
        public int Id { get; set; }
        public string WorkPlaceName { get; set; }
        public string Position { get; set; }
        public System.DateTime StartYear { get; set; }
        public System.DateTime EndYear { get; set; }
        public int CvId { get; set; }
    
        public virtual Cvs Cvs { get; set; }
    }
}
