//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Languages
    {
        public int Id { get; set; }
        public int LanguageLevel { get; set; }
        public string LanguageName { get; set; }
        public int ProgrammingLanguageLevel { get; set; }
        public string ProgrammingLanguageName { get; set; }
        public Nullable<int> Cv_id { get; set; }
    
        public virtual Cvs Cvs { get; set; }
    }
}
